ALTER TABLE `tb_arquivos` CHANGE `NM_TIPO` `DS_TIPO` ENUM('APRESENTAÇÃO','AQUISIÇÃO','COTAÇÃO DE PREÇO','CERTIDÃO NEGATIVA','DESPACHO','MEMORANDO','OFÍCIO','PARECER','PUBLICAÇÃO NO DIÁRIO','RELATÓRIO','RESPOSTA AO INTERESSADO','TERMO DE REFERÊNCIA','CERTIFICADO','CHECKLIST') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_STATUS` `DS_STATUS` ENUM('ATIVO','INATIVO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_ANEXO` `DS_ANEXO` VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_arquivos` CHANGE `DS_STATUS` `DS_STATUS` ENUM('ATIVO','INATIVO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `tb_arquivos` CHANGE `ID_SERVIDOR_ENVIADO` `ID_SERVIDOR_DESTINO` INT(20) NULL DEFAULT NULL;

ALTER TABLE `tb_servidores` CHANGE `NM_STATUS` `DS_STATUS` ENUM('ATIVO','INATIVO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `tb_servidores` CHANGE `NM_SERVIDOR` `DS_NOME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_servidores` CHANGE `CD_SERVIDOR` `DS_CPF` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_servidores` CHANGE `NM_ARQUIVO_FOTO` `DS_FOTO` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'default.jpg';

ALTER TABLE `tb_servidores` CHANGE `NM_FUNCAO` `DS_FUNCAO` ENUM('PROTOCOLO','SUPERINTENDENTE','ASSESSOR TÉCNICO','TÉCNICO ANALISTA','GABINETE','CONTROLADOR','TI','COMUNICAÇÃO','CHEFE DE GABINETE','TÉCNICO ANALISTA CORREÇÃO') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE `tb_comunicacao` CHANGE `NM_CHAPEU` `DS_CHAPEU` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_TITULO` `DS_TITULO` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_INTERTITULO` `DS_INTERTITULO` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `NM_CREDITOS` `DS_CREDITOS` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `NM_STATUS` `DS_STATUS` ENUM('OCULTADA','PUBLICADA','INATIVA') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_setores` CHANGE `NM_SETOR` `DS_NOME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_setores` CHANGE `CD_SETOR` `DS_ABREVIACAO` VARCHAR(11) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_chamados` CHANGE `NM_PROBLEMA` `DS_PROBLEMA` VARCHAR(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_NATUREZA` `DS_NATUREZA` ENUM('WORD','EXCEL','POWER POINT','TRELLO','SIAFEM','SIAPI','COMPUTADOR OU PEÇA COM DEFEITO','INTERNET','COMPARTILHAMENTO DE PASTA','IMPRESSORA','PAINEL DE GESTÃO','OUTRO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_STATUS` `DS_STATUS` ENUM('ABERTO','RESOLVIDO','ENCERRADO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_AVALIACAO` `DS_AVALIACAO` ENUM('PÉSSIMO','RUIM','REGULAR','BOM','EXCELENTE','SEM AVALIAÇÃO') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE `tb_chamados` CHANGE `DS_STATUS` `DS_STATUS` ENUM('ABERTO','RESOLVIDO','ENCERRADO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'ABERTO';

ALTER TABLE `tb_chamados` CHANGE `DS_STATUS` `DS_STATUS` ENUM('ABERTO','FECHADO','ENCERRADO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'ABERTO';

UPDATE tb_chamados SET DS_STATUS = 'FECHADO' WHERE DS_STATUS = '';

ALTER TABLE `tb_chamados` CHANGE `DS_AVALIACAO` `DS_AVALIACAO` ENUM('PÉSSIMO','RUIM','REGULAR','BOM','EXCELENTE','SEM AVALIAÇÃO') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'SEM AVALIAÇÃO';

ALTER TABLE `tb_historico_chamados` CHANGE `NM_MENSAGEM` `TX_MENSAGEM` VARCHAR(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_historico_chamados` CHANGE `TX_MENSAGEM` `TX_MENSAGEM` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_historico_chamados` CHANGE `ID_CHAMADO` `ID_REFERENTE` INT(20) NOT NULL;

ALTER TABLE `tb_historico_chamados` CHANGE `NM_ACAO` `DS_ACAO` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

UPDATE tb_historico_chamados SET DS_ACAO = 'FECHAMENTO' WHERE DS_ACAO = 'RESOLUÇÃO';

ALTER TABLE `tb_historico_chamados` CHANGE `DS_ACAO` `DS_ACAO` ENUM('ABERTURA','FECHAMENTO','AVALIAÇÃO','ENCERRAMENTO','MENSAGEM') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

UPDATE `tb_historico_chamados` SET TX_MENSAGEM = 'ABRIU UM NOVO CHAMADO' WHERE TX_MENSAGEM = 'SOLICITOU AJUDA';

UPDATE `tb_historico_chamados` SET tx_mensagem = 'FECHOU O CHAMADO' WHERE tx_mensagem = 'RESOLVEU O CHAMADO';

ALTER TABLE `tb_comunicacao` CHANGE `DS_STATUS` `DS_STATUS` ENUM('OCULTADA','PUBLICADA','INATIVA') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'OCULTADA';

ALTER TABLE `tb_anexos_comunicacao` CHANGE `NM_LEGENDA` `DS_LEGENDA` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `NM_CREDITOS` `DS_CREDITOS` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `NM_ARQUIVO` `DS_ARQUIVO` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_assuntos_processos` CHANGE `NM_ASSUNTO` `DS_NOME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_TIPO` `DS_TIPO` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_orgaos` CHANGE `CD_ORGAO` `DS_ABREVIACAO` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_ORGAO` `DS_NOME` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_processos` CHANGE `CD_PROCESSO` `DS_NUMERO` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_DETALHES` `DS_DETALHES` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_INTERESSADO` `DS_INTERESSADO` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_STATUS` `DS_STATUS` ENUM('EM ANDAMENTO','FINALIZADO PELO SETOR','FINALIZADO PELO GABINETE','ARQUIVADO','SAIU') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_processos` CHANGE `DS_STATUS` `DS_STATUS` ENUM('EM ANDAMENTO','FINALIZADO PELO SETOR','FINALIZADO PELO GABINETE','ARQUIVADO','SAIU') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'EM ANDAMENTO';

ALTER TABLE `tb_processos` CHANGE `ID_SETOR_LOCALIZACAO` `ID_SETOR_LOCALIZACAO` INT(20) NULL, CHANGE `ID_SERVIDOR_LOCALIZACAO` `ID_SERVIDOR_LOCALIZACAO` INT(20) NULL;

ALTER TABLE `tb_historico_processos` CHANGE `ID_PROCESSO` `ID_REFERENTE` INT(20) NOT NULL;

ALTER TABLE `tb_historico_processos` CHANGE `NM_MENSAGEM` `TX_MENSAGEM` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_historico_processos` CHANGE `NM_ACAO` `DS_ACAO` ENUM('ABERTURA','TRAMITAÇÃO','MUDANÇA DE PRAZO','MENSAGEM','CONCLUSÃO','FINALIZAÇÃO','ARQUIVAMENTO','PRAZO','AÇÃO','SAÍDA','VOLTAR','RESPONSÁVEIS','CRIAÇÃO','DESARQUIVAMENTO','EDIÇÃO','FINALIZAÇÃO DESFEITA','URGENTE','LÍDER','CONFIRMAR PROCESSO','RETORNAR PROCESSO','APENSAR','ANEXAR','EXCLUIR ANEXO','REMOVER RESPONSÁVEL','SOBRESTADO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

UPDATE tb_historico_processos SET DS_ACAO = 'ANEXAR' WHERE DS_ACAO = 'AÇÃO';

ALTER TABLE `tb_historico_processos` CHANGE `DS_ACAO` `DS_ACAO` ENUM('ABERTURA','TRAMITAÇÃO','MUDANÇA DE PRAZO','MENSAGEM','CONCLUSÃO','FINALIZAÇÃO','ARQUIVAMENTO','PRAZO','SAÍDA','VOLTAR','RESPONSÁVEIS','CRIAÇÃO','DESARQUIVAMENTO','EDIÇÃO','FINALIZAÇÃO DESFEITA','URGENTE','LÍDER','CONFIRMAR PROCESSO','RETORNAR PROCESSO','APENSAR','ANEXAR','EXCLUIR ANEXO','REMOVER RESPONSÁVEL','SOBRESTADO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE tb_processos DROP ID_SETOR_LOCALIZACAO;

ALTER TABLE `tb_historico_processos` CHANGE `DS_ACAO` `DS_ACAO` ENUM('ABERTURA','TRAMITAÇÃO','MUDANÇA DE PRAZO','MENSAGEM','CONCLUSÃO','FINALIZAÇÃO','ARQUIVAMENTO','PRAZO','SAÍDA','VOLTAR','RESPONSÁVEIS','CRIAÇÃO','DESARQUIVAMENTO','EDIÇÃO','FINALIZAÇÃO DESFEITA','URGENTE','LÍDER','CONFIRMAR PROCESSO','RETORNAR PROCESSO','APENSAR','ANEXAR','EXCLUIR ANEXO','REMOVER RESPONSÁVEL','SOBRESTADO','REMOVER APENSO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

update `tb_historico_processos` set DS_ACAO='REMOVER APENSO' WHERE TX_MENSAGEM = 'REMOVEU UM APENSO DO PROCESSO';

ALTER TABLE `tb_processos` ADD `BL_RECEBIDO` ENUM('0','1') NOT NULL AFTER `DT_PRAZO`;

ALTER TABLE `tb_processos` CHANGE `BL_RECEBIDO` `BL_RECEBIDO` TINYINT(1) NOT NULL DEFAULT '0';

UPDATE tb_processos b INNER JOIN (SELECT A.ID_PROCESSO, A.BL_RECEBIDO, MAX(A.DT_TRAMITACAO) FROM tb_tramitacao_processos A GROUP BY ID_PROCESSO) a ON b.ID = a.ID_PROCESSO set b.BL_RECEBIDO = a.BL_RECEBIDO;

ALTER TABLE `tb_processos` CHANGE `BL_RECEBIDO` `BL_RECEBIDO` TINYINT(1) NOT NULL DEFAULT '1';

UPDATE tb_processos SET BL_RECEBIDO = 1 WHERE DS_STATUS IN ('ARQUIVADO', 'SAIU');

ALTER TABLE `tb_documentos` CHANGE `NM_TIPO` `DS_TIPO` ENUM('APRESENTAÇÃO','AQUISIÇÃO','COTAÇÃO DE PREÇO','CERTIDÃO NEGATIVA','DESPACHO','MEMORANDO','OFÍCIO','PARECER','PUBLICAÇÃO NO DIÁRIO','RELATÓRIO','RESPOSTA AO INTERESSADO','TERMO DE REFERÊNCIA','CHECKLIST','CERTIFICADO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_ANEXO` `DS_ANEXO` VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

UPDATE tb_historico_processos SET DS_ACAO = 'CRIAÇÃO DE DOCUMENTO' WHERE DS_ACAO = 'CRIAÇÃO';

update tb_historico_processos set DS_ACAO = 'CRIAÇÃO DE DOCUMENTO' WHERE DS_ACAO = 'ANEXAR';

UPDATE tb_historico_processos set DS_ACAO = 'EXCLUSÃO DE DOCUMENTO' WHERE DS_ACAO = 'EXCLUIR ANEXO';

ALTER TABLE `tb_historico_processos` CHANGE `DS_ACAO` `DS_ACAO` ENUM('ABERTURA','TRAMITAÇÃO','MUDANÇA DE PRAZO','MENSAGEM','CONCLUSÃO','FINALIZAÇÃO','ARQUIVAMENTO','PRAZO','SAÍDA','VOLTAR','RESPONSÁVEIS','DESARQUIVAMENTO','EDIÇÃO','FINALIZAÇÃO DESFEITA','URGENTE','LÍDER','CONFIRMAR PROCESSO','RETORNAR PROCESSO','APENSAR','CRIAÇÃO DE DOCUMENTO','EXCLUSÃO DE DOCUMENTO','REMOVER RESPONSÁVEL','SOBRESTADO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_processos_sobrestados` CHANGE `NM_JUSTIFICATIVA` `DS_JUSTIFICATIVA` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `NM_STATUS` `DS_STATUS` ENUM('SOLICITADO','ACEITO','RECUSADO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'SOLICITADO';

ALTER TABLE `tb_processos_sobrestados` CHANGE `DS_JUSTIFICATIVA` `DS_JUSTIFICATIVA` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

UPDATE tb_historico_processos SET TX_MENSAGEM = 'ANEXOU UM DOCUMENTO AO PROCESSO' WHERE DS_ACAO = '';

UPDATE tb_historico_processos SET DS_ACAO = 'CRIAÇÃO DE DOCUMENTO' WHERE DS_ACAO = '';

ALTER TABLE `tb_processos_apensados` CHANGE `ID_PROCESSO_MAE` `ID_PROCESSO` INT(20) NOT NULL;

ALTER TABLE `tb_historico_processos` CHANGE `DS_ACAO` `DS_ACAO` ENUM('ABERTURA','TRAMITAÇÃO','MUDANÇA DE PRAZO','MENSAGEM','CONCLUSÃO','FINALIZAÇÃO','ARQUIVAMENTO','PRAZO','SAÍDA','VOLTAR','RESPONSÁVEIS','DESARQUIVAMENTO','EDIÇÃO','FINALIZAÇÃO DESFEITA','URGENTE','LÍDER','CONFIRMAR PROCESSO','RETORNAR PROCESSO','APENSAR','CRIAÇÃO DE DOCUMENTO','EXCLUSÃO DE DOCUMENTO','REMOVER RESPONSÁVEL','SOBRESTADO','REMOÇÃO DE APENSO') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_documentos` CHANGE `DS_TIPO` `DS_TIPO` ENUM('APRESENTAÇÃO','AQUISIÇÃO','COTAÇÃO DE PREÇO','CERTIDÃO NEGATIVA','DESPACHO','MEMORANDO','OFÍCIO','PARECER','PUBLICAÇÃO NO DIÁRIO','RELATÓRIO','RESPOSTA AO INTERESSADO','TERMO DE REFERÊNCIA','CHECKLIST','CERTIFICADO','LAUDO PERICIAL','ANEXOS AO LAUDO','ANEXOS AO RELATÓRIO','RAC') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;


ALTER TABLE `tb_arquivos` CHANGE `DS_TIPO` `DS_TIPO` ENUM('APRESENTAÇÃO','AQUISIÇÃO','COTAÇÃO DE PREÇO','CERTIDÃO NEGATIVA','DESPACHO','MEMORANDO','OFÍCIO','PARECER','PUBLICAÇÃO NO DIÁRIO','RELATÓRIO','RESPOSTA AO INTERESSADO','TERMO DE REFERÊNCIA','CHECKLIST','CERTIFICADO','LAUDO PERICIAL','ANEXOS AO LAUDO','ANEXOS AO RELATÓRIO','RAC') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_historico_processos` CHANGE `DT_MENSAGEM` `DT_ACAO` DATETIME NOT NULL;

ALTER TABLE `tb_historico_chamados` CHANGE `DT_MENSAGEM` `DT_ACAO` DATETIME NOT NULL;

ALTER TABLE `tb_anexos_comunicacao` ADD FOREIGN KEY (`ID_COMUNICACAO`) REFERENCES `tb_comunicacao`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE `tb_arquivos` ADD FOREIGN KEY (`ID_SERVIDOR_CRIACAO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 

ALTER TABLE `tb_arquivos` ADD FOREIGN KEY (`ID_SERVIDOR_DESTINO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_assuntos_processos` ADD FOREIGN KEY (`ID_SETOR_RESPONSAVEL`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_chamados` ADD FOREIGN KEY (`ID_SERVIDOR_REQUISITANTE`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_documentos` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE `tb_documentos` ADD FOREIGN KEY (`ID_SERVIDOR_CRIACAO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_historico_chamados` ADD FOREIGN KEY (`ID_REFERENTE`) REFERENCES `tb_chamados`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT; 

ALTER TABLE `tb_historico_chamados` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_historico_processos` ADD FOREIGN KEY (`ID_REFERENTE`) REFERENCES `tb_processos`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT; 

ALTER TABLE `tb_historico_processos` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_ASSUNTO`) REFERENCES `tb_assuntos_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 

ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_ORGAO_INTERESSADO`) REFERENCES `tb_orgaos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 

ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_SERVIDOR_LOCALIZACAO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_SETOR_RESPONSAVEL`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_processos_apensados` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE `tb_processos_apensados` ADD FOREIGN KEY (`ID_PROCESSO_APENSADO`) REFERENCES `tb_processos`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE `tb_processos_sobrestados` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE `tb_processos_sobrestados` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT; 

ALTER TABLE `tb_processos_sobrestados` ADD FOREIGN KEY (`ID_SERVIDOR_SOLICITANTE`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 

ALTER TABLE `tb_processos_sobrestados` ADD FOREIGN KEY (`ID_SERVIDOR_RESPOSTA`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_responsaveis_processos` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT; 

ALTER TABLE `tb_responsaveis_processos` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_servidores` ADD FOREIGN KEY (`ID_SETOR`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_setores` ADD FOREIGN KEY (`ID_SETOR_SUBORDINADO`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE CASCADE ON UPDATE RESTRICT; 

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_SERVIDOR_ORIGEM`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_SETOR_ORIGEM`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_SERVIDOR_DESTINO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_SETOR_DESTINO`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; 

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_SERVIDOR_CONFIRMOU`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;